### ISSUE TITLE
Browser freezes when exception is thrown in NgOnInit

### ISSUE THREAD

**Issue by Moulde** [bugsnag/bugsnag-angular#10] opened 2018-04-04 10:34 UTC
I posted this in the bugsnag-js project, but this seems to be related to angular.
The reason i posted it in bugsnag-js before, is due to the bugsnag.js logs just before freezing (see below)

https://github.com/bugsnag/bugsnag-js/issues/337

Comment from other issue:

It seems that an exception in the ngOnInit function in angular, is bad for business, but before I included bugsnag.js and bugsnag-angular, it would just break routing, and you'd have to reload the page. But after including bugsnag, it completely freezes the browser tab, and you'd have to resort to the chrome task manager to close the tab, and I havent found a way to close the tab in safari.,

### Expected behavior
I added a text exception:
`throw Error('test exception'); `
in my anuglar application component ngInit method, and expect the application to fail, and then send the error to bugsnag via the angular exception handler.

### Observed behavior
Instead my browser freezes, and the last thing i see in the console is:

```
  | decirc | @ | bugsnag.js:1955
-- | -- | -- | --
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | stringify | @ | bugsnag.js:1920
  | _$payload_25 | @ | bugsnag.js:1965
  | sendReport | @ | bugsnag.js:2048
  | notify | @ | bugsnag.js:1208
  | BugsnagErrorHandler.handleError | @ | index.js:33
  | (anonymous) | @ | core.js:5914
  | ZoneDelegate.invoke | @ | zone.js:388
  | Zone.run | @ | zone.js:138


```

### Steps to reproduce
I followed the guide on how to integrate bugsnag in angular, and it works fine when i throw an exception in the mentioned component **constructor**, but when I do it in the ngInit method, it freezes the app completely, this happens in both safari and chrome.

The bugsnag notify method example, from the docs, also works fine.

### Version
    "bugsnag-angular": "^2.0.0",
    "bugsnag-js": "^4.4.0",

**Comment by bengourley** [comment] 2018-04-04 10:54
Closing because I believe this is a duplicate of #3.

**Closed as completed by bengourley** 2018-04-04 10:54 UTC
